/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICarmelRegistry,
  ICarmelRegistryInterface,
} from "../../../contracts/CarmelTreasury.sol/ICarmelRegistry";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "keyId",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "username",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "message",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct CarmelFingerprint",
        name: "fingerprint",
        type: "tuple",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICarmelRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ICarmelRegistryInterface {
    return new Interface(_abi) as ICarmelRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICarmelRegistry {
    return new Contract(address, _abi, runner) as unknown as ICarmelRegistry;
  }
}
