/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CarmelTreasury__factory } from "./CarmelTreasury__factory";
export { ICarmelRegistry__factory } from "./ICarmelRegistry__factory";
