/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CarmelTreasury } from "./CarmelTreasury";
export type { ICarmelRegistry } from "./ICarmelRegistry";
