/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CarmelRegistry } from "./CarmelRegistry";
export type { ICarmelVerifier } from "./ICarmelVerifier";
