/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CarmelRegistry__factory } from "./CarmelRegistry__factory";
export { CarmelRegistry2__factory } from "./CarmelRegistry2__factory";
