/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CarmelRegistry__factory } from "./CarmelRegistry__factory";
export { ICarmelVerifier__factory } from "./ICarmelVerifier__factory";
