/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelinCommunityContracts from "./openzeppelin-community-contracts";
export type { openzeppelinCommunityContracts };
